import { SignIn, SignInButton, SignOutButton, UserButton, useSession, useUser } from "@clerk/clerk-react";
import Head from "next/head";
import Link from "next/link";
import { Input } from "postcss";
import { useState } from "react";
import { date } from "zod";
import { Header } from "~/components/Header";


import { RouterOutputs, api } from "~/utils/api";
const TABS = ["Home", "Fantasy Judo Rules", "My Team" , "Create or Join a League", "View Leaderboard"] as const;


const CreateTestWizard = () => {
  const {data} = api.test.getAll.useQuery();
  const {user} = useUser();
  console.log(data)


  

  
  const [input, setInput] = useState("");
  
const ctx = api.useContext();


const {mutate, isLoading : isPosting} = api.test.create.useMutation({
  onSuccess: () =>{
  setInput("")
  void ctx.test.getAll.invalidate()
}
}
);


if (!user) return null;



return (<div >
  
  <div>
    {data?.map((test) => (<div key={test.test.id}>{test.test.content}</div>))}
  </div>

  <div>
  <input
        placeholder="Content"
        className="grow bg-grey outline-none"
        type="text"
        value= {input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            e.preventDefault();
            if (input !== "") {
              mutate({ content: input });
            }
          }
        }}
        disabled={isPosting}
  />
  </div>
        
 <button onClick={() => mutate({content : input})} >Post</button>
</div>
);

};

const CreateNameWizard = () => {
  const {data} = api.name.getAll.useQuery();
  const {user} = useUser();
  console.log(data)


  

  
  const [input, setInput] = useState("");
  
const ctx = api.useContext();


const {mutate, isLoading : isPosting} = api.name.create.useMutation({
  onSuccess: () =>{
  setInput("")
  void ctx.name.getAll.invalidate()
}
}
);


if (!user) return null;



return (<div className="bg-sky-300	">
  
  
  <div>
    {data?.map((name) => (<div key={name.name.id}>{name.name.name}</div>))}
  </div>

  <div>
  <input
        placeholder="Content"
        className="grow bg-grey outline-none"
        type="text"
        value= {input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            e.preventDefault();
            if (input !== "") {
              mutate({ name: input });
            }
          }
        }}
        disabled={isPosting}
  />
  </div>
        
 <button onClick={() => mutate({name : input})} >Post</button>
</div>
);
 
};




const CreatePostWizard = () => {
  const {data} = api.post.getAll.useQuery();
  const {user} = useUser();
  console.log(data)
  

  
  const [input, setInput] = useState("");
  
const ctx = api.useContext();


const {mutate, isLoading : isPosting} = api.post.create.useMutation({
  onSuccess: () =>{
  setInput("")
  void ctx.post.getAll.invalidate()
}
}
);


if (!user) return null;



return (<div >
  
  
  <div className="flex justify-between items-center mx-auto max-w-screen-xl p-4 bg-slate-200">
  
  <input
        placeholder="Content"
        className="grow bg-transparent outline-none"
        type="text"
        value= {input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            e.preventDefault();
            if (input !== "") {
              mutate({ content: input });
            }
          }
        }}
        disabled={isPosting}
        />
        
 <button onClick={() => mutate({content : input})} >Post</button>
</div>
</div> 
);

};

type PostWithUser = RouterOutputs["post"]["getAll"][number]


const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  console.log(author);
  return (
    <div key={post.id} className="border-b border-slate-400 p-8">
              {post.content}
              <span>  @{author?.username || author?.fullname}</span>
            </div>
  );

}
const Feed = () => {
  const {data, isLoading: postsLoading } = api.post.getAll.useQuery();

  if (postsLoading) return <div>loading</div>;
 

  if (!data) return <div>Something went wrong</div>


  return (
    <div className="flex grow flex-col overflow-y-scroll">
      {[...data].map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  )

}






export default function Home() {

  const [selectedTab, setSelectedTab] =
    useState<(typeof TABS)[number]>("Home");

    const session = useSession();


  const user = useUser();

  const { data } = api.post.getAll.useQuery();

console

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Header/>
      <main className="flex min-h-screen flex-col items-center justify-center">
          <h1 className="font-bold">Hello {user.user?.firstName}</h1>
        <div className="">
        {session.isSignedIn === true && (
          <div className="flex">
            {TABS.map((tab) => {
              return (
                <button
                key={tab}
                className={`flex-grow p-2 hover:bg-gray-200 focus-visible:bg-gray-200 ${
                  tab === selectedTab
                  ? "border-b-4 border-b-blue-500 font-bold"
                  : ""
                }`}
                  onClick={() => setSelectedTab(tab)
                  }
                >
                  {tab}
                </button>
              );
            })}
          </div>
        )}

        
      {selectedTab === "Home" ? <CreateNameWizard /> :<div></div>}


        {selectedTab === "Fantasy Judo Rules" ? <CreatePostWizard /> : <div></div>}
        {selectedTab === "Team" ? <CreateTestWizard /> : <div></div>}
        


         <Feed/>
      
        
        </div>
        

      </main>
    </>
  );
}

function func() {
  throw new Error("Function not implemented.");
}
