
import { useSession, useUser } from "@clerk/clerk-react";
import Head from "next/head";
import { useState } from "react";
import { Leaderboard } from "~/components/Leaderboard";
import { Header } from "~/components/Header";
import { MyTeam } from "~/components/MyTeam";
import { Rules } from "~/components/Rules";
import MediaQuery from 'react-responsive'


import { FaBookOpen } from "react-icons/fa";
import { RiTeamFill } from "react-icons/ri";
import { IoCreate } from "react-icons/io5";
import { MdLeaderboard } from "react-icons/md";





import { AiFillHome } from 'react-icons/ai';

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import { Admin } from "~/components/Admin";
//import { Tab } from "~/components/Start";
 

const TABS = ["Home", "Fantasy Judo Rules", "My Team" , "Create or Join a League", "View Leaderboard"] as const;
const TABSsm = [<AiFillHome key="Home"/>,<FaBookOpen key="Fantasy Judo Rules"/>, <RiTeamFill key="My Team"/>, <IoCreate key="Create or Join a League"/>, <MdLeaderboard key="View Leaderboard"/>]




const Start = () => {
  const user = useUser();
  console.log(user)

  const TABS = ["Home", "Fantasy Judo Rules", "My Team" , "Create or Join a League", "View Leaderboard"] as const;


  const [selectedTab, setSelectedTab] =
  useState<(typeof TABS)[number]>("Home");



  return ( <div>
  
          {TABS.map((prop) => {
            return (
              <div key={prop} className="text-center"><button
              key={prop}
              className={`flex-grow w-80 text-lg p-2 m-8 bg-slate-400 rounded-full hover:bg-gray-200 focus-visible:bg-gray-200 ${
                (prop === selectedTab && selectedTab !== "Home")
                ? "border-b-4 border-b-blue-500 font-bold"
                : "border-black bg-slate-100 "
              }`}
                onClick={() => setSelectedTab(prop)
                }
              >
                {prop}
              </button>
              </div>
            );
          })}
  
  </div>)
      };




const CreatePostWizard = () => {
  const {user} = useUser();
  

  
  const [input, setInput] = useState("");
  
const ctx = api.useContext();


const {mutate, isLoading : isPosting} = api.post.create.useMutation({
  onSuccess: () =>{
  setInput("")
  void ctx.post.getAll.invalidate()
}
}
);


if (!user) return null;



return (<div >
  
  
  <div className="flex justify-between items-center mx-auto max-w-screen-xl p-4 bg-slate-200">
  
  <input
        placeholder="Content"
        className="grow bg-transparent outline-none"
        type="text"
        value= {input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            e.preventDefault();
            if (input !== "") {
              mutate({ content : input });
            }
          }
        }}
        disabled={isPosting}
        />
        
 <button onClick={() => mutate({content : input})} >Post</button>
</div>
</div> 
);

};

type PostWithUser = RouterOutputs["post"]["getAll"][number]


const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  console.log(author);
  return (
    <div key={post.id} className="border-b border-slate-400 p-8">
              {post.content}
              <span>  @{author?.username ?? author?.fullname}</span>
            </div>
  );

}
const Feed = () => {
  const {data, isLoading: postsLoading } = api.post.getAll.useQuery();

  if (postsLoading) return <div>loading</div>;
 

  if (!data) return <div>Something went wrong</div>


  return (
    <div className="flex grow flex-col overflow-y-scroll">
      {[...data].map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  )

}






export default function Home() {
  const {user} = useUser();
  console.log(user?.id)


  const [selectedTab, setSelectedTab] =
    useState<(typeof TABS)[number]>("Home");

    const [selectedTabsm, setSelectedTabsm] =
    useState<(typeof TABSsm)[number]>(<AiFillHome/>
);

    const session = useSession();
  const tabs = void selectedTabsm.key 
  console.log(tabs)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Header/>
          <div>
       <nav className="bg-slate-400 dark:bg-gray-1200">
       <div>
       <MediaQuery maxWidth={480}>
        <div>
        {session.isSignedIn === true&& (
          <div className="flex">
            {TABSsm.map((tab) => {
              return (
                <button
                key={tab}
                className={`flex-grow p-2 hover:bg-slate-300 focus-visible:bg-gray-200 ${
                  tab === selectedTabsm
                  ? "border-b-4 border-b-blue-500 font-bold"
                  : ""
                  
                }`}
                  onClick={() => setSelectedTabsm(tab)
                  }
                >
                  {tab}
                </button>
              );
            })}
            </div>)}
            </div>
            </MediaQuery>
            </div>



       {/*<MediaQuery minWidth={481}>*/}
        <div>
        {session.isSignedIn === true && (
          <div className="flex">
            {TABS.map((tab) => {
              return (
                <button
                key={tab}
                className={`flex-grow place-content-center p-2 hover:bg-slate-300 focus-visible:bg-gray-200 ${
                  tab === selectedTab
                  ? "border-b-4 border-b-blue-500 font-bold"
                  : ""
                  
                }`}
                  onClick={() => setSelectedTab(tab)
                  }
                >
                  {tab}
                </button>
              );
            })}
            </div>)}
            </div>
           {/* </MediaQuery>*/}
            </nav>
    </div>
    


      <main className="flex min-h-screen flex-col items-center justify-center">
    
      <div>{user?.id === "user_2Wl222xbsT9joVm2ZzORl5i3AL2" ? <Admin/>: <div></div>}</div>

      <div className="">
      {(selectedTab === "Home"                    || selectedTabsm.key === "Home")                    ? <Start /> :<div></div>                                     }
      {(selectedTab === "Fantasy Judo Rules"      || selectedTabsm.key === "Fantasy Judo Rules")      ? <><Rules /><Feed /><CreatePostWizard /> </>: <div></div>   }
      {(selectedTab === "View Leaderboard"        || selectedTabsm.key === "View Leaderboard")        ? <Leaderboard/> : <div></div>}
      {(selectedTab === "My Team"                 || selectedTabsm.key === "My Team")                 ? <MyTeam /> : <div></div>                                   }
      {(selectedTab === "Create or Join a League" || selectedTabsm.key === "Create or Join a League") ? <p>soon available</p>: <div></div>                          }
        </div>
      </main>
    </>
  );
}


